---
controller:
  clusterAdminAccess: true
applicationSet:
  enabled: true
server:
  ingress:
    enabled: false
extraDeploy:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/instance: argocd
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: argocd-cmd-params-cm
        app.kubernetes.io/part-of: argocd
      name: argocd-cmd-params-cm
    data:
      application.namespaces: "*"
